# Generated by Django 5.2.3 on 2025-07-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('title_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField()),
                ('translated_title', models.CharField(max_length=500)),
                ('original_text', models.TextField()),
                ('preview', models.CharField(max_length=500)),
                ('translated_post', models.TextField()),
            ],
            options={
                'db_table': 'titles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=500)),
                ('check_news', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('type_of_feed', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'urls',
                'managed': False,
            },
        ),
    ]
